// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsWH_gl02EkOpGqTSw75-fVrZf31pdthM',
    appId: '1:633201173529:web:1afbde87af2c2c94687688',
    messagingSenderId: '633201173529',
    projectId: 'to-do-task-luminar',
    authDomain: 'to-do-task-luminar.firebaseapp.com',
    storageBucket: 'to-do-task-luminar.firebasestorage.app',
    measurementId: 'G-4PGQWQRB57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqfcXcqVCfEIgHAORYqjcWJMTYxrS-Omk',
    appId: '1:633201173529:android:eeaf6b31a51feb7b687688',
    messagingSenderId: '633201173529',
    projectId: 'to-do-task-luminar',
    storageBucket: 'to-do-task-luminar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC99AUPljMlyHtnEN8z1drhFKhU4hwt74',
    appId: '1:633201173529:ios:e8da3a2243ccba47687688',
    messagingSenderId: '633201173529',
    projectId: 'to-do-task-luminar',
    storageBucket: 'to-do-task-luminar.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC99AUPljMlyHtnEN8z1drhFKhU4hwt74',
    appId: '1:633201173529:ios:e8da3a2243ccba47687688',
    messagingSenderId: '633201173529',
    projectId: 'to-do-task-luminar',
    storageBucket: 'to-do-task-luminar.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsWH_gl02EkOpGqTSw75-fVrZf31pdthM',
    appId: '1:633201173529:web:62775aa48b9efadf687688',
    messagingSenderId: '633201173529',
    projectId: 'to-do-task-luminar',
    authDomain: 'to-do-task-luminar.firebaseapp.com',
    storageBucket: 'to-do-task-luminar.firebasestorage.app',
    measurementId: 'G-WRHXEFKSTM',
  );

}